Controladores Basicos Tabla Pedidos
Emanuel-Palestino/Elinge-Boneless-Servidor pull request #3
Opened 2021-12-12 23:29 UTC by HassamVasquez

2021-12-19 03:36 UTC, Emanuel-Palestino requested changes
Ya sólo modifica eso que te comenté tanto para finalizados como no finalizados del cliente. Y no olvides compilar tus cambios y probarlos.

2021-12-19 03:36 UTC, Emanuel-Palestino commented on src/routes/pedidosRoutes.ts
> +		this.router.get('/clienteFinalizados/:idCliente', pedidosController.listarPedidosFinalizadosCliente);
La idea era: /cliente/finalizados/:idCliente
O puedes poner: /finalizadosPorCliente/:idCliente

2021-12-20 04:25 UTC, HassamVasquez commented on src/routes/pedidosRoutes.ts
> +		this.router.get('/clienteFinalizados/:idCliente', pedidosController.listarPedidosFinalizadosCliente);
Ok

2021-12-20 05:03 UTC, Emanuel-Palestino approved these changes
Correcto, se ve bien

2021-12-20 05:05 UTC, merged